### ISSUE TITLE
Git clone error.

### ISSUE THREAD

**Issue by p3yot3** [lodyagin/compcoin#1]
Cloning from repo results in missing files & git error: "unable to check out".  Downloading the zip also results in missing files.

Please check your configuration/settings.

**Comment by p3yot3** [comment]
Still...........

Cloning into 'compcoin'...
remote: Counting objects: 31302, done.
remote: Compressing objects: 100% (182/182), done.
remote: Total 31302 (delta 198), reused 208 (delta 124), pack-reused 30996
Receiving objects: 100% (31302/31302), 37.71 MiB | 255.00 KiB/s, done.
Resolving deltas: 100% (23571/23571), done.
Checking connectivity... done.
warning: remote HEAD refers to nonexistent ref, unable to checkout.

**Comment by lodyagin** [comment]
Sorry, I got notifications 3 days ago but didn't recognize that it was an open issue, thought just some technical report about a temporary trouble from github.

You shouldn't checkout master, there is no such branch here (but may be it is better to add).
Nevertheless, now it works as:

 git clone -b compcoin-v1.3 https://github.com/lodyagin/compcoin.git

**Comment by p3yot3** [comment]
That worked, thanks.  Yeah, having a master branch is always better & is usually the norm.

regards.
